# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/home.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        Form.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 59, 1081, 661))
        self.stackedWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Account = QtWidgets.QWidget()
        self.Account.setObjectName("Account")
        self.pushButton = QtWidgets.QPushButton(parent=self.Account)
        self.pushButton.setGeometry(QtCore.QRect(310, 200, 93, 29))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(parent=self.Account)
        self.label_4.setGeometry(QtCore.QRect(0, -10, 1081, 721))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/Netflix-Premium-Gratis-en-2022-Apk-e1659877674993.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(parent=self.Account)
        self.widget_2.setGeometry(QtCore.QRect(330, 90, 691, 431))
        self.widget_2.setStyleSheet("background-color: rgba(0, 0, 0, 150); /* nền tối mờ */\n"
"    border-radius: 10px;")
        self.widget_2.setObjectName("widget_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 91, 21))
        self.label_6.setStyleSheet("color: white;\n"
"    font-size: 12px;\n"
"    padding-left: 8px;\n"
"    padding-bottom: 2px;\n"
"    background-color: transparent;")
        self.label_6.setObjectName("label_6")
        self.txt_name = QtWidgets.QLineEdit(parent=self.widget_2)
        self.txt_name.setGeometry(QtCore.QRect(50, 60, 191, 26))
        self.txt_name.setObjectName("txt_name")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(50, 110, 63, 20))
        self.label_7.setStyleSheet("color: white;\n"
"    font-size: 12px;\n"
"    padding-left: 8px;\n"
"    padding-bottom: 2px;\n"
"    background-color: transparent;")
        self.label_7.setObjectName("label_7")
        self.txt_email = QtWidgets.QLineEdit(parent=self.widget_2)
        self.txt_email.setGeometry(QtCore.QRect(50, 140, 191, 26))
        self.txt_email.setObjectName("txt_email")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(50, 190, 91, 20))
        self.label_8.setStyleSheet("color: white;\n"
"    font-size: 12px;\n"
"    padding-left: 8px;\n"
"    padding-bottom: 2px;\n"
"    background-color: transparent;")
        self.label_8.setObjectName("label_8")
        self.txt_birthday = QtWidgets.QDateEdit(parent=self.widget_2)
        self.txt_birthday.setGeometry(QtCore.QRect(60, 230, 110, 26))
        self.txt_birthday.setObjectName("txt_birthday")
        self.txt_gender = QtWidgets.QComboBox(parent=self.widget_2)
        self.txt_gender.setGeometry(QtCore.QRect(50, 310, 76, 26))
        self.txt_gender.setObjectName("txt_gender")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.label_34 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_34.setGeometry(QtCore.QRect(60, 270, 91, 20))
        self.label_34.setStyleSheet("color: white;\n"
"    font-size: 12px;\n"
"    padding-left: 8px;\n"
"    padding-bottom: 2px;\n"
"    background-color: transparent;")
        self.label_34.setObjectName("label_34")
        self.btn_save_account = QtWidgets.QPushButton(parent=self.widget_2)
        self.btn_save_account.setGeometry(QtCore.QRect(180, 370, 100, 32))
        self.btn_save_account.setObjectName("btn_save_account")
        self.label_5 = QtWidgets.QLabel(parent=self.Account)
        self.label_5.setGeometry(QtCore.QRect(140, 200, 71, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/user-solid.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.btn_avatar = QtWidgets.QPushButton(parent=self.Account)
        self.btn_avatar.setGeometry(QtCore.QRect(40, 100, 281, 261))
        self.btn_avatar.setStyleSheet("background-color: rgba(0, 0, 0, 150); /* nền tối mờ */\n"
"    border-radius: 10px;")
        self.btn_avatar.setText("")
        self.btn_avatar.setObjectName("btn_avatar")
        self.stackedWidget.addWidget(self.Account)
        self.Detail = QtWidgets.QWidget()
        self.Detail.setObjectName("Detail")
        self.lbl_detail_name = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_name.setGeometry(QtCore.QRect(540, 70, 471, 31))
        self.lbl_detail_name.setStyleSheet("color: rgb(255, 255, 255); font-size: 20px;")
        self.lbl_detail_name.setText("")
        self.lbl_detail_name.setObjectName("lbl_detail_name")
        self.lbl_detail_director = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_director.setGeometry(QtCore.QRect(500, 200, 471, 21))
        self.lbl_detail_director.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_director.setText("")
        self.lbl_detail_director.setObjectName("lbl_detail_director")
        self.lbl_detail_release_date = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_release_date.setGeometry(QtCore.QRect(500, 230, 471, 21))
        self.lbl_detail_release_date.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_release_date.setText("")
        self.lbl_detail_release_date.setObjectName("lbl_detail_release_date")
        self.lbl_detail_genre = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_genre.setGeometry(QtCore.QRect(500, 260, 471, 21))
        self.lbl_detail_genre.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_genre.setText("")
        self.lbl_detail_genre.setObjectName("lbl_detail_genre")
        self.lbl_detail_main_actor = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_main_actor.setGeometry(QtCore.QRect(500, 290, 471, 21))
        self.lbl_detail_main_actor.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_main_actor.setText("")
        self.lbl_detail_main_actor.setObjectName("lbl_detail_main_actor")
        self.lbl_detail_description = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_description.setGeometry(QtCore.QRect(500, 330, 541, 121))
        self.lbl_detail_description.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_description.setText("")
        self.lbl_detail_description.setWordWrap(True)
        self.lbl_detail_description.setObjectName("lbl_detail_description")
        self.lbl_detail_duration = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_duration.setGeometry(QtCore.QRect(500, 460, 200, 21))
        self.lbl_detail_duration.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_duration.setText("")
        self.lbl_detail_duration.setObjectName("lbl_detail_duration")
        self.lbl_detail_age_rating = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_age_rating.setGeometry(QtCore.QRect(720, 460, 200, 21))
        self.lbl_detail_age_rating.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_age_rating.setText("")
        self.lbl_detail_age_rating.setObjectName("lbl_detail_age_rating")
        self.lbl_detail_rating = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_rating.setGeometry(QtCore.QRect(940, 460, 100, 21))
        self.lbl_detail_rating.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_rating.setText("")
        self.lbl_detail_rating.setObjectName("lbl_detail_rating")
        self.lbl_detail_image = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_image.setGeometry(QtCore.QRect(10, 80, 471, 391))
        self.lbl_detail_image.setText("")
        self.lbl_detail_image.setScaledContents(True)
        self.lbl_detail_image.setObjectName("lbl_detail_image")
        self.btn_favorite = QtWidgets.QPushButton(parent=self.Detail)
        self.btn_favorite.setGeometry(QtCore.QRect(500, 500, 131, 31))
        self.btn_favorite.setStyleSheet("border:none; background:none")
        self.btn_favorite.setText("")
        self.btn_favorite.setObjectName("btn_favorite")
        self.btn_watch = QtWidgets.QPushButton(parent=self.Detail)
        self.btn_watch.setGeometry(QtCore.QRect(180, 478, 151, 51))
        self.btn_watch.setStyleSheet("border:none;\n"
"background:none")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_watch.setIcon(icon)
        self.btn_watch.setObjectName("btn_watch")
        self.stackedWidget.addWidget(self.Detail)
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.searchContainer = QtWidgets.QWidget(parent=self.Home)
        self.searchContainer.setGeometry(QtCore.QRect(40, 20, 1000, 50))
        self.searchContainer.setStyleSheet("background-color: rgba(0, 0, 0, 100);")
        self.searchContainer.setObjectName("searchContainer")
        self.txt_search = QtWidgets.QLineEdit(parent=self.searchContainer)
        self.txt_search.setGeometry(QtCore.QRect(20, 10, 300, 30))
        self.txt_search.setStyleSheet("background-color: white; border-radius: 15px; padding: 5px;")
        self.txt_search.setObjectName("txt_search")
        self.btn_search = QtWidgets.QPushButton(parent=self.searchContainer)
        self.btn_search.setGeometry(QtCore.QRect(340, 10, 80, 30))
        self.btn_search.setStyleSheet("background-color: #E50914; color: white; border-radius: 15px;")
        self.btn_search.setObjectName("btn_search")
        self.video_container = QtWidgets.QWidget(parent=self.Home)
        self.video_container.setGeometry(QtCore.QRect(40, 90, 1000, 500))
        self.video_container.setStyleSheet("background-color: transparent;")
        self.video_container.setObjectName("video_container")
        self.favorite_container = QtWidgets.QWidget(parent=self.Home)
        self.favorite_container.setGeometry(QtCore.QRect(40, 610, 1000, 200))
        self.favorite_container.setStyleSheet("background-color: rgba(0, 0, 0, 50);")
        self.favorite_container.setObjectName("favorite_container")
        self.stackedWidget.addWidget(self.Home)
        self.Watch = QtWidgets.QWidget()
        self.Watch.setObjectName("Watch")
        self.volumeBar = QtWidgets.QSlider(parent=self.Watch)
        self.volumeBar.setGeometry(QtCore.QRect(920, 600, 160, 22))
        self.volumeBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeBar.setObjectName("volumeBar")
        self.videoWidget = QtWidgets.QWidget(parent=self.Watch)
        self.videoWidget.setGeometry(QtCore.QRect(20, 30, 1061, 511))
        self.videoWidget.setStyleSheet("background:rgb(0, 0, 0)")
        self.videoWidget.setObjectName("videoWidget")
        self.volumeBtn = QtWidgets.QPushButton(parent=self.Watch)
        self.volumeBtn.setGeometry(QtCore.QRect(820, 590, 93, 29))
        self.volumeBtn.setStyleSheet("border:none;\n"
"background:none")
        self.volumeBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/volume-high-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.volumeBtn.setIcon(icon1)
        self.volumeBtn.setObjectName("volumeBtn")
        self.videoName = QtWidgets.QLabel(parent=self.Watch)
        self.videoName.setGeometry(QtCore.QRect(40, 560, 301, 31))
        self.videoName.setStyleSheet("border:none;\n"
"background:none;\n"
"color: white;")
        self.videoName.setObjectName("videoName")
        self.timeLabel = QtWidgets.QLabel(parent=self.Watch)
        self.timeLabel.setGeometry(QtCore.QRect(160, 610, 121, 20))
        self.timeLabel.setStyleSheet("border:none;\n"
"background:none;\n"
"color: white;")
        self.timeLabel.setObjectName("timeLabel")
        self.durationBar = QtWidgets.QSlider(parent=self.Watch)
        self.durationBar.setGeometry(QtCore.QRect(290, 610, 511, 22))
        self.durationBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.durationBar.setObjectName("durationBar")
        self.playBtn = QtWidgets.QPushButton(parent=self.Watch)
        self.playBtn.setGeometry(QtCore.QRect(500, 560, 111, 41))
        self.playBtn.setStyleSheet("border:none;\n"
"background:none")
        self.playBtn.setText("")
        self.playBtn.setIcon(icon)
        self.playBtn.setObjectName("playBtn")
        self.stackedWidget.addWidget(self.Watch)
        self.label_23 = QtWidgets.QLabel(parent=Form)
        self.label_23.setGeometry(QtCore.QRect(0, 0, 141, 61))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/images-removebg-preview.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.btn_home = QtWidgets.QPushButton(parent=Form)
        self.btn_home.setGeometry(QtCore.QRect(150, 20, 111, 31))
        self.btn_home.setStyleSheet("color: white;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"")
        self.btn_home.setObjectName("btn_home")
        self.pushButton_17 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_17.setGeometry(QtCore.QRect(270, 20, 111, 31))
        self.pushButton_17.setStyleSheet("color: white;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_18.setGeometry(QtCore.QRect(390, 20, 111, 31))
        self.pushButton_18.setStyleSheet("color: white;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_20 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_20.setGeometry(QtCore.QRect(500, 20, 101, 29))
        self.pushButton_20.setStyleSheet("color: white;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_16 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_16.setGeometry(QtCore.QRect(610, 20, 161, 29))
        self.pushButton_16.setStyleSheet("color: white;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_19 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_19.setGeometry(QtCore.QRect(800, 20, 141, 29))
        self.pushButton_19.setStyleSheet("border:none; background:none")
        self.pushButton_19.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/magnifying-glass-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_19.setIcon(icon2)
        self.pushButton_19.setObjectName("pushButton_19")
        self.btn_profile = QtWidgets.QPushButton(parent=Form)
        self.btn_profile.setGeometry(QtCore.QRect(970, 20, 93, 29))
        self.btn_profile.setStyleSheet("border:none;\n"
"background:none")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/user-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_profile.setIcon(icon3)
        self.btn_profile.setObjectName("btn_profile")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.label_6.setText(_translate("Form", "Username"))
        self.label_7.setText(_translate("Form", "Email"))
        self.label_8.setText(_translate("Form", "Birthday"))
        self.txt_gender.setItemText(0, _translate("Form", "None"))
        self.txt_gender.setItemText(1, _translate("Form", "Male"))
        self.txt_gender.setItemText(2, _translate("Form", "Female"))
        self.label_34.setText(_translate("Form", "Gender"))
        self.btn_save_account.setText(_translate("Form", "Save"))
        self.btn_watch.setText(_translate("Form", "Play"))
        self.txt_search.setPlaceholderText(_translate("Form", "Search movies..."))
        self.btn_search.setText(_translate("Form", "Search"))
        self.videoName.setText(_translate("Form", "Video name"))
        self.timeLabel.setText(_translate("Form", "00:00/00:00"))
        self.btn_home.setText(_translate("Form", "Trang chủ"))
        self.pushButton_17.setText(_translate("Form", "Phim Thình"))
        self.pushButton_18.setText(_translate("Form", "Phim"))
        self.pushButton_20.setText(_translate("Form", "Mới thêm"))
        self.pushButton_16.setText(_translate("Form", "Danh sách của tôi"))
        self.btn_profile.setText(_translate("Form", "Profile"))
