# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/Netflix-Premium-Gratis-en-2022-Apk-e1659877674993.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(380, 80, 341, 391))
        self.widget.setStyleSheet("\n"
"    background-color: rgba(0, 0, 0, 150); /* nền tối mờ */\n"
"    border-radius: 10px;")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 151, 41))
        self.label_2.setStyleSheet("color: white;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 1px;\n"
" background-color: rgba(0, 0, 0, 150); /* nền tối mờ */")
        self.label_2.setObjectName("label_2")
        self.txt_email = QtWidgets.QLineEdit(parent=self.widget)
        self.txt_email.setGeometry(QtCore.QRect(50, 90, 251, 71))
        self.txt_email.setStyleSheet("background-color: #333333;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-size: 16px;")
        self.txt_email.setObjectName("txt_email")
        self.txt_password = QtWidgets.QLineEdit(parent=self.widget)
        self.txt_password.setGeometry(QtCore.QRect(50, 170, 251, 61))
        self.txt_password.setStyleSheet("background-color: #333333;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-size: 16px;")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.btn_login = QtWidgets.QPushButton(parent=self.widget)
        self.btn_login.setGeometry(QtCore.QRect(50, 240, 251, 41))
        self.btn_login.setStyleSheet("background-color: #e50914; /* Màu đỏ đặc trưng */\n"
"    color: white; /* Màu chữ trắng */\n"
"    border: none; /* Không có viền */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Cỡ chữ */\n"
"    border-radius: 4px; /* Bo góc nhẹ */")
        self.btn_login.setObjectName("btn_login")
        self.checkBox = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox.setGeometry(QtCore.QRect(20, 290, 121, 24))
        self.checkBox.setStyleSheet("color: white;\n"
"    font-size: 14px;\n"
"    font-family: Arial, sans-serif;")
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(230, 290, 71, 20))
        self.label_3.setStyleSheet("color: white;\n"
"    font-size: 14px;\n"
"    text-decoration: underline;")
        self.label_3.setObjectName("label_3")
        self.btn_eye = QtWidgets.QPushButton(parent=self.widget)
        self.btn_eye.setGeometry(QtCore.QRect(260, 180, 31, 29))
        self.btn_eye.setStyleSheet("border: none;\n"
"background: none;")
        self.btn_eye.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye.setIcon(icon)
        self.btn_eye.setObjectName("btn_eye")
        self.btn_register = QtWidgets.QPushButton(parent=self.widget)
        self.btn_register.setGeometry(QtCore.QRect(180, 330, 131, 41))
        self.btn_register.setStyleSheet("background-color: #e50914; /* Màu đỏ đặc trưng */\n"
"    color: white; /* Màu chữ trắng */\n"
"    border: none; /* Không có viền */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Cỡ chữ */\n"
"    border-radius: 4px; /* Bo góc nhẹ */")
        self.btn_register.setObjectName("btn_register")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Sign in"))
        self.txt_email.setPlaceholderText(_translate("Form", "email or phone number"))
        self.txt_password.setPlaceholderText(_translate("Form", "password"))
        self.btn_login.setText(_translate("Form", "Sign in"))
        self.checkBox.setText(_translate("Form", "Remember me"))
        self.label_3.setText(_translate("Form", "Need help?"))
        self.btn_register.setText(_translate("Form", "Sign up"))
