# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/signup.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1081, 721))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/Netflix-Premium-Gratis-en-2022-Apk-e1659877674993.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(380, 30, 371, 571))
        self.label_2.setStyleSheet(" background-color: rgba(0, 0, 0, 150); /* nền tối mờ */\n"
"    border-radius: 10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(500, 60, 131, 41))
        self.label_3.setStyleSheet(" color: white;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 1px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(424, 120, 91, 20))
        self.label_4.setStyleSheet("background-color:  rgb(0, 0, 0);\n"
"color: white;\n"
"font-size: 20px")
        self.label_4.setObjectName("label_4")
        self.txt_name = QtWidgets.QLineEdit(parent=Form)
        self.txt_name.setGeometry(QtCore.QRect(420, 160, 241, 61))
        self.txt_name.setStyleSheet("background-color: rgba(0, 0, 0, 0.6);  /* Nền đen mờ */\n"
"    color: white;                         /* Chữ trắng */\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* Viền trắng mờ */\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"")
        self.txt_name.setObjectName("txt_name")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(420, 220, 151, 21))
        self.label_5.setStyleSheet("background-color:  rgb(0, 0, 0);\n"
"color: white;\n"
"font-size: 20px")
        self.label_5.setObjectName("label_5")
        self.txt_email = QtWidgets.QLineEdit(parent=Form)
        self.txt_email.setGeometry(QtCore.QRect(420, 250, 241, 71))
        self.txt_email.setStyleSheet("background-color: rgba(0, 0, 0, 0.6);  /* Nền đen mờ */\n"
"    color: white;                         /* Chữ trắng */\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* Viền trắng mờ */\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"")
        self.txt_email.setObjectName("txt_email")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(430, 320, 151, 31))
        self.label_6.setStyleSheet("background-color:  rgb(0, 0, 0);\n"
"color: white;\n"
"font-size: 20px")
        self.label_6.setObjectName("label_6")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(420, 350, 241, 71))
        self.txt_password.setStyleSheet("background-color: rgba(0, 0, 0, 0.6);  /* Nền đen mờ */\n"
"    color: white;                         /* Chữ trắng */\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* Viền trắng mờ */\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(420, 420, 161, 31))
        self.label_9.setStyleSheet("background-color:  rgb(0, 0, 0);\n"
"color: white;\n"
"font-size: 20px")
        self.label_9.setObjectName("label_9")
        self.txt_confirm_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_confirm_password.setGeometry(QtCore.QRect(420, 460, 251, 51))
        self.txt_confirm_password.setStyleSheet("background-color: rgba(0, 0, 0, 0.6);  /* Nền đen mờ */\n"
"    color: white;                         /* Chữ trắng */\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* Viền trắng mờ */\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;")
        self.txt_confirm_password.setObjectName("txt_confirm_password")
        self.btn_register = QtWidgets.QPushButton(parent=Form)
        self.btn_register.setGeometry(QtCore.QRect(480, 520, 151, 41))
        self.btn_register.setStyleSheet("background-color: #e50914; /* Màu đỏ đặc trưng */\n"
"    color: white; /* Màu chữ trắng */\n"
"    border: none; /* Không có viền */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Cỡ chữ */\n"
"    border-radius: 4px; /* Bo góc nhẹ */")
        self.btn_register.setObjectName("btn_register")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(644, 550, 93, 29))
        self.btn_login.setObjectName("btn_login")
        self.btn_eye_p = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_p.setGeometry(QtCore.QRect(610, 370, 51, 31))
        self.btn_eye_p.setStyleSheet("background: none;\n"
"border: none;")
        self.btn_eye_p.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/DongQuan/python-app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.btn_eye_cp = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_cp.setGeometry(QtCore.QRect(620, 460, 51, 31))
        self.btn_eye_cp.setStyleSheet("background: none;\n"
"border: none;")
        self.btn_eye_cp.setText("")
        self.btn_eye_cp.setIcon(icon)
        self.btn_eye_cp.setObjectName("btn_eye_cp")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Sign up"))
        self.label_4.setText(_translate("Form", "Username"))
        self.txt_name.setPlaceholderText(_translate("Form", "Username"))
        self.label_5.setText(_translate("Form", "Email"))
        self.txt_email.setPlaceholderText(_translate("Form", "Email"))
        self.label_6.setText(_translate("Form", "Password"))
        self.txt_password.setPlaceholderText(_translate("Form", "Password"))
        self.label_9.setText(_translate("Form", "Confirm password"))
        self.txt_confirm_password.setPlaceholderText(_translate("Form", "Confirm password"))
        self.btn_register.setText(_translate("Form", "Sign Up"))
        self.btn_login.setText(_translate("Form", "Login"))
